CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
email VARCHAR(20) NOT NULL UNIQUE ,
password VARCHAR NOT NULL,
first_name VARCHAR(20)NOT NULL,
last_name VARCHAR(20)NOT NULL,
profile_photo VARCHAR DEFAULT NULL,
isArtist BOOLEAN NOT NULL DEFAULT false,
isPremium BOOLEAN NOT NULL DEFAULT false
);
