FROM openjdk:18
#ARG JAR_FILE=target/*jar
WORKDIR /var/www/recommendations-app
#ADD src /src
#COPY ${JAR_FILE} app.jar
ENTRYPOINT ["tail", "-f", "/dev/null"]
#ENTRYPOINT ["java","-jar","/recommendations-app/app.jar"]

